### PR TITLE
Will/refactor tree

### PR DESCRIPTION
**Pull request by skybluecircles**

### CODE REVIEW

**Comment by oschwald** [comment]
There are a number of outstanding branches that should be merged before stuff is moved around.

**Comment by skybluecircles** [comment]
This was more for me to be able to focus on the freezing / thawing and to let Dave see the changes. I just prefaced the title with [WIP].

**Comment by oschwald** [comment]
Ok, as long as you realize we likely won't be able to use this code as it would be very easy to lose a change and cause a memory leak when merging/rebasing it.

**Comment by skybluecircles** [comment]
Yes, understood.

**Pull request closed without merging**
